# -*- coding: utf-8 -*-
"""PS10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxzIK1D0BPk_-8042QlKL9aXkXp1XMYk
"""

import pandas as pd

data=pd.read_csv('IRIS.csv')
print(data)

null_values = data.isnull().sum()
print(null_values)

data.describe()

print("Rows : = "+str(data.shape[0]))
print("Cols : = "+str(data.shape[1]))

unique_vals=data['species'].unique()
print(unique_vals)

species_setosa = data[data['species'] == 'Iris-setosa']
print(species_setosa)

species_versicolor = data[data['species'] == 'Iris-versicolor']
print(species_versicolor)

species_virginica = data[data['species'] == 'Iris-virginica']
print(species_virginica)

merged_subset = pd.concat([species_virginica, species_setosa], ignore_index=True)
print(merged_subset)

sorted_data_ascending = data.sort_values(by='sepal_length')
print(sorted_data_ascending)

sorted_data_descending = data.sort_values(by='sepal_length',ascending=False)
print(sorted_data_descending)

transposed_data = data.transpose()
print(transposed_data)

melted_data = pd.melt(data, id_vars=['sepal_length', 'species'], var_name='Metric', value_name='Value')
print(melted_data)

wide_data = melted_data.pivot_table(index=['sepal_length', 'species'], columns='Metric', values='Value')
print(wide_data)