# -*- coding: utf-8 -*-
"""PS18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EEKv3sVnbi67rnwIIlJSDjXGzofCL76C
"""

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('heart.csv')
print(data)

data.describe()

# HISTOGRAM
plt.hist(data['age'], bins=10)
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Histogram Of Age Feature')
plt.show()

# PIE CHART
target_counts = data['target'].value_counts()
plt.pie(target_counts, labels=['No Heart Disease', 'Heart Disease'], autopct='%1.1f%%')
plt.title('Distribution of Heart Disease')
plt.show()
# Pokemon

# BOX PLOT
plt.boxplot(data['chol'])
plt.xlabel('Cholesterol')
plt.title('Distribution of Cholesterol')
plt.show()

# BOX PLOT
plt.boxplot(data['age'])
plt.xlabel('Age')
plt.title('Distribution of Age')
plt.show()

# SCATTER PLOT
plt.scatter(data['age'], data['chol'])
plt.xlabel('Age')
plt.ylabel('Cholestrol')
plt.title('Age vs Cholestrol')
plt.show()

# BAR CHART
cp_counts = data['cp'].value_counts()
plt.bar(cp_counts.index, cp_counts.values)
plt.xlabel('Chest Pain Type')
plt.ylabel('Frequency')
plt.title('Distribution of Chest Pain Type')
plt.show()