# -*- coding: utf-8 -*-
"""PS9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Brqx6CgnGuC-qf5P3K5uhJxbB6fxJda
"""

import pandas as pd

data=pd.read_csv('Dataset_Facebook.csv',delimiter=';')
print(data)

data.describe()

print("row : = "+str(data.shape[0]))
print("col : = "+str(data.shape[1]))

unique_val=data['Type'].unique()
print(unique_val)

posts_photo = data[data['Type'] == 'Photo']
print(posts_photo)

posts_status = data[data['Type'] == 'Status']
print(posts_status)

posts_link = data[data['Type'] == 'Link']
print(posts_link)

posts_video = data[data['Type'] == 'Video']
print(posts_video)

merged_subset = pd.concat([posts_photo, posts_link], ignore_index=True)
print(merged_subset)

sorted_data_ascending = data.sort_values(by='Page total likes',ascending=False)
print(sorted_data_ascending)

sorted_data_descending = data.sort_values(by='Page total likes')
print(sorted_data_descending)

transposed_data = data.transpose()
print(transposed_data)

melted_data = pd.melt(data, id_vars=['Type', 'Page total likes'], var_name='Metric', value_name='Value')
print(melted_data)

wide_data = melted_data.pivot_table(index=['Type', 'Page total likes'], columns='Metric', values='Value')
print(wide_data)



data1=pd.read_csv('Dataset_Facebook.csv')
print(data1)